import Head from "next/head";
import React from "react";
import Header from "./Header";

const Layout = ({ children, user, title }) => {
  return (
    <div>
      <Head>
        <title>
          {title ||
            "Disney+ | The streaming home of Disney, Pixar, Marvel, Star Wars, NatGeo and Star"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header session={user} />
      {children}
    </div>
  );
};

export default Layout;
